### ISSUE TITLE
2.0 14318 Crashing on Nvidia Shield 

### ISSUE THREAD

**Issue by porterballs** [Bankaimaster999/Dolphin-MMJR2#24]
Hello I’ve tried reinstalling with no luck! I receive the allow access to files dialogue but after that the app just refuses to open, crashes as soon as you try and open it.

**Comment by sspacelynx** [comment]
Thank you, we have received other reports of the app crashing on an Nvidia Shield, and we apologise for that. Sadly we don't have one of those devices in our testers group, would you be able to join our Discord to help us figure this out?

**Comment by porterballs** [comment]
Sure no problem! I have already joined the discord which I assume if the one you are talking about. My username is porterballs#0474 happy to help out
