### ISSUE TITLE
discord invitation is invalid

### ISSUE THREAD

**Issue by Haisom** [Bankaimaster999/Dolphin-MMJR2#49]
not sure if this is the right place but the link invitation is invalid, is this intentional?

**Comment by Gamemulatorer** [comment]
https://github.com/Bankaimaster999/Dolphin-MMJR2/commit/40d45a2f907d4a0cd2d49922bdee88bb36601d52#commitcomment-55928162

**Comment by Bankaimaster999** [comment]
The links work just fine ... visit https://github.com/Bankaimaster999/Dolphin-MMJR2 scroll down to the discord link ....

**Comment by Gamemulatorer** [comment]
LOL
![Uploading Screenshot_2021-09-05-13-43-58-809_com.discord.jpg…]()

**Comment by Haisom** [comment]
It's working now, thanks!
