### ISSUE TITLE
gamepad problem

### ISSUE THREAD

**Issue by AkameYT007** [Bankaimaster999/Dolphin-MMJR2#56]
so after the update i need to remap the control every time i go out and back, it shows it is mapped but it doesnt work, it only works again if i remap

**Comment by AkameYT007** [comment]
so after the update i need to remap the control every time i go out and back, it shows it is mapped but it doesnt work, it only works again if i remap

**Comment by Bankaimaster999** [comment]
ok 
https://www.reddit.com/r/EmulationOnAndroid/comments/qbtjv9/thanks_for_supporting_mmjrmmjr2_so_far_but/
