### ISSUE TITLE
Twilight Princess black screen when custom textures are enabled but OK with the original MMJR

### ISSUE THREAD

**Issue by nullsurfer** [Bankaimaster999/Dolphin-MMJR2#57]
I would like to use MMJR2 instead of the original because Gecko codes work, however custom textures do not. TP is stuck on a black screen and not responding when custom textures are enabled, but plays just fine when disabled. Custom textures also worked just fine on MMJR (the original).

I'm using Henriko Magnifico's texture pack.

**Comment by nullsurfer** [comment]
Ok, I found a workaround. Run the game first with custom textures disabled. While running, go to Dolphin's Quick Settings, click the arrow on the top right, and enable custom textures from there. The game might hang for a while, but the custom textures will load eventually.

**Comment by Bankaimaster999** [comment]
That's not a workaround ... that's just the textures taking time to load properly for that texture pack you using ...

**Comment by nullsurfer** [comment]
> That's not a workaround ... that's just the textures taking time to load properly for that texture pack you using ...

Probably not. I left Dolphin open on my phone for maybe 10 minutes with custom textures enabled but the game still won't load. Then I tried opening the game with custom textures disabled, then enabled custom textures while running. It only took like a minute to load the textures.
