### ISSUE TITLE
No display on desktop mode

### ISSUE THREAD

**Issue by Azy77** [Bankaimaster999/Dolphin-MMJR2#58]
Hi, I have an Oppo Find X3 Pro with Snapdragon 888.

In non desktop mode when I connect my phone via usb c to a monitor it connects and displays ok but there are borders all over the place as it mirrors my phone.

When I enable desktop mode from developer options then connect phone to external display via Usb C there is no video display of any and all games (GC, Wii) on my monitor. The sound works fine and all the dolphin menus can be displayed just not the actual game.

Desktop mode on the 2nd screen works fine for all my other apps including retroarch and citra just not dolphin.

Is there a workaround for this? Thanks

**Comment by Bankaimaster999** [comment]
Not sure about this issue nor a workaround BUT this should shed more light on MMJR development = https://www.reddit.com/r/EmulationOnAndroid/comments/qbtjv9/thanks_for_supporting_mmjrmmjr2_so_far_but/
