### ISSUE TITLE
Wii Games Crash in Landscape Mode

### ISSUE THREAD

**Issue by chrisasma103** [Bankaimaster999/Dolphin-MMJR2#60]
This was also a problem with Dolphin Official that was fixed in a developer build. If you launch a Wii game in landscape mode, it will sometimes not load up at all and the app will crash. If you launch a game in portrait mode, it will never crash.

**Comment by Bankaimaster999** [comment]
If you can find the PR update where Dolphin Official fixed the issue then I can squeeze in some time to work on it but I don't have much time to investigate that and run tests.
So if you can help me along with that I could do that.

**Comment by chrisasma103** [comment]
I'll look into it!

**Comment by chrisasma103** [comment]
My rudimentary notes are here: https://notes.io/PZAD

It looks to me that the first working version is 5.0-15561, which incorporates [PR #10228](https://github.com/dolphin-emu/dolphin/pull/10228). 5.0-15559 has the crash, and every version I've tested above this doesn't seem to crash.

**Comment by Bankaimaster999** [comment]
> My rudimentary notes are here: https://notes.io/PZAD
> 
> It looks to me that the first working version is 5.0-15561, which incorporates [PR #10228](https://github.com/dolphin-emu/dolphin/pull/10228). 5.0-15559 has the crash, and every version I've tested above this doesn't seem to crash.

OK I have added in this PR and a couple of others and it will come in 2.0-15110. So you will let me know how that goes.

**Comment by Bankaimaster999** [comment]
Updated to the latest source code as well so you'll let me know if there is a positive change for you.

**Comment by chrisasma103** [comment]
This seems to have fixed it. Thank you very much
