### ISSUE TITLE
Warning: the disc that was about to be inserted could not be found

### ISSUE THREAD

**Issue by tribilin9191** [Bankaimaster999/Dolphin-MMJR2#61]
I'm playing RE0 and it doesn't want to change to disc 2 and that message appears

**Comment by Bankaimaster999** [comment]
1.  I'm no really back working on MMJR2
2.  If Dolphin Official already has this fixed; then if you can find the relevant PR for it I can add it into the code during my free time.

**Comment by tribilin9191** [comment]
Thanks you

**Comment by Bankaimaster999** [comment]
> I'm playing RE0 and it doesn't want to change to disc 2 and that message appears

Updated to the latest dolphin official source code so you'll have to check to see if there is a positive change for you and let me know
