### ISSUE TITLE
Frequent Crashes in Wind Waker

### ISSUE THREAD

**Issue by chrisasma103** [Bankaimaster999/Dolphin-MMJR2#62]
Hi, I just updated to the latest version of MMJR2, and while it fixed the portrait mode issue, it introduced an even greater issue. I played Wind Waker over maybe 1-2 hours, and it crashed 4 times. The first two crashes came with error messages (that I forgot to write down), but the next two didn't. The app just closed.
Crash 1: Right as Phantom Ganon was defeated (before the cutscene)
Crash 2: Walking in the connecting outside hallways of the forsaken fortress.
Crash 3: Turning my boat as I was leaving Underwater Hyrule.
Crash 4: Leaving a fairy fountain (the cutscene where you float away)

I don't remember how many of the quick hacks I had on. However, before the update, I had no issues at all with crashing. Now, it seems to crash at random.
I just turned out panic handler and all messages to see if anything comes up. I know this isn't the most specific issue, but I never had an issue like this before the update.

**Comment by Bankaimaster999** [comment]
I would need to see a log of this or to recreate the issue. It could also be related to a corrupt save state introducing issues.

**Comment by chrisasma103** [comment]
I figured as much. I haven't used any save states, btw. If it crashes again, I have panic handlers on. Is there anything else I should enable for help with debugging?

**Comment by chrisasma103** [comment]
Crash 5: Crashed during fast travel. No panic handler message came up or anything. I was using all 4 quick hacks.
Crash 6: Crashed firing a fire arrow at a bat. No panic handler message came up, but I remembered to enable logs. Here is the log for that playsession https://www.mediafire.com/file/numoj095gdi3afh/dolphin.log/file

**Comment by Bankaimaster999** [comment]
After the later updates is it still happening?

**Comment by chrisasma103** [comment]
I will check. Btw, the version that came out before the one that caused crashes (2 updates before the current one) hasn't caused any crashes at all. I'll update to the latest version and test. Thanks for all the hard work, though. I use MMJR2 because Dolphin official doesn't play nice with frontends

**Comment by chrisasma103** [comment]
There are still crashes. I will upload the logs as soon as I can

**Comment by chrisasma103** [comment]
Log after crash 1 (note: I did boot the game back up again for a little bit before closing it and getting the log, I think): https://www.mediafire.com/file/uaitghh41vd92az/dolphin_%25281%2529.log/file

Log after crash 2: https://www.mediafire.com/file/t0rrjih2ak3kf4l/dolphin_%25282%2529.log/file
