### ISSUE TITLE
"check for updates at startup" loop

### ISSUE THREAD

**Issue by Zip111** [Bankaimaster999/Dolphin-MMJR2#63]
No idea what's the problem i tried reinstalling deleted old dolphine data etc.

**Comment by Themailkid** [comment]
What worked for me were:
Uninstall newest version, install older version and then update using the update inside the app.

**Comment by azukaar** [comment]
Have the same issue,
Orignally had an older version, upgraded, and it was always displaying an error: "IOS FS failed to write new FST" or something, so I deleted the MMJR folder, thinking may be the old config was not compatible, but then I know have this same update loop, the app shows "do you want to update auto ?" neither pressing yes or no does anything aside from re-showing the same pop up.
I think this new version is failling to write in the config folder on some newer Android version for permission reasons, or something like this.
I am using the Samsung Galaxy Fold 3 with Android 11

**Comment by Nube79** [comment]
The loop appears when you do a clean install, when upgrading it doesn't happen if there is already a configuration saved.

**Comment by Themailkid** [comment]
> Have the same issue, Orignally had an older version, upgraded, and it was always displaying an error: "IOS FS failed to write new FST" or something, so I deleted the MMJR folder, thinking may be the old config was not compatible, but then I now have this same update loop, the app shows "do you want to update auto ?" neither pressing yes or no does anything aside from re-showing the same pop up. I think this new version is failling to write in the config folder on some newer Android version for permission reasons, or something like this. I am using the Samsung Galaxy Fold 3 with Android 11

Its happening the same with me.

**Comment by Bankaimaster999** [comment]
Yea I noticed this is happening for Android 11 and up users ... its probably related to permissions and further changes necessary to access storage
