### ISSUE TITLE
Serious drop in performance

### ISSUE THREAD

**Issue by persianstryx** [Bankaimaster999/Dolphin-MMJR2#64]
The version that was released right before this one, version 15.110 was able to push 2k resolution (720p) on low end devices. Which was very impressive. Unfortunately since this latest version implemented the open source code from the official version it came with all it's detrimental effects on performance as well. It seems this app unfortunately took 1 step forward and two steps back. What I managed to do was revert to the previous version 15.110 and extract the open source code system files from the latest version on to the previous version and it worked fine. I am very much looking forward to their next update as it is a very interesting point in time for this app. Since it is struggling to get the best of both worlds implementing the best the underground has to offer for performance, but at the same time trying to strive for excellence and perfection as the newer versions of the official dolphin. I really like the auto update checker in app that is very cool..Anyways, my two cents are. If this app stays in it's trajectory that focuses mostly on performance and keeps making a few small changes here and there to the format and accessibility options one day it will surpass the official version. Also since this is by all means an underground version of the official and there is no need to try and imitate the official. I really think the previous text format on the in game screen from it's predecessor MMJR looks a lot nicer and sharper than this new text format that is the same one as the official. I just think that the text format of the official looks very clunky and you can always notice it there on screen (if you're like me and toggle fps on because you like to know what you currently running on) so I really like the old one because it is smaller and neater (Not to mention it shows your full specs) but mainly because it is kinder on the eye. You hardly notice it when you're playing, but when you need to it's there...Overall this app shows promise and I believe that if it's stays in it's own trajectory and tries to strive there it will without a doubt surpass the official version.....

**Comment by Bankaimaster999** [comment]
thanks for praise but its not really meant to compare to official ... due to very few people working on it and even the other forks; it really doesn't make sense to stay behind it. 
I'm only updating it right now because I got nothing better to do at the moment and people are requesting some things. 
So its better to stay on Dolphin official for the long run.
