### ISSUE TITLE
Star Wars: The Clone Wars unplayable performance

### ISSUE THREAD

**Issue by Zip111** [Bankaimaster999/Dolphin-MMJR2#65]
The game is very slow on Dolphin, 20-40 fps with many drops, and somehow it is even slower on MMJR. Gpu usage maxes out at 10% and cpu is usually around 30% but I saw short spikes up 100%. In some areas it goes up to 50 fps but the usage is the same. Only the title screen has 60 fps but still some drops.
Android 11 Snapdragon 860. 2.0-15110 or any recent Dolphin version.

I know it's not necessarily an issue of MMJR but it seems like a special case, maybe someone else can test this game with other hardware or settings? Tried a bunch of different ones but no improvement at all. 

This game was also the last to run on Dolphin and it needed MMU and LLE enabled, so maybe it has something to do with that?

**Comment by Bankaimaster999** [comment]
I'll look into the MMU option ... no promises on performance though

**Comment by Zip111** [comment]
Thank you! It would be interesting to know what the problem is since apparently it runs fine on PC nowadays. I tried enabling MMU and LLE, but it's not needed anymore and only slows things down as it says in the options. Maybe this game just needs a more powerful Cpu like 888 or 8 Gen 1.
