### ISSUE TITLE
Error: ios_fs failed to write new fst

### ISSUE THREAD

**Issue by dochankpin** [Bankaimaster999/Dolphin-MMJR2#68]
Hi guys!
I have a problem installing/upgrading to this new version of Dolphin MMJR 2 v2.0-15989.
When opening Dolphin after installation, a small white window appears, with the following message:
IOS_FS Failed to Write new FST.
And a screen also appears, asking if I accept to make updates when starting,
and this screen does not come out.
And it's also not saving settings, game folder shortcuts, or menu options anymore.
Thank you in advance for your attention, patience of all.
Thanks again and see you later, bye.

My Phone Specs:
Motorola Moto G100
Adreno: 650
SnapDragon: 870
Ram: 12GB

Error Scrrenshot
![ERROR](https://user-images.githubusercontent.com/89654166/151884256-9bf50381-da3b-4619-aa43-234b1aca6244.png)

**Comment by nullsurfer** [comment]
Same here on my OnePlus 6

**Comment by raelbbb** [comment]
É isso mesmo está aparecendo esse erro tomara que eu não perca o meu progresso todinho no jogo

**Comment by EmaMiranda** [comment]
Same here, android 11, Xiaomi Mi 9T pro

**Comment by Artyom-Krivosheev** [comment]
Same. Poco X3 Pro with SD 860. After updating to the latest version (via mmjr 2 updator inside this fork), it crashed while launching games. After I reinstalled it manually, it shows the update screen pop up. It doesn't matter what you choose. After pressing yes or no it infinitely spawns the same pop up now.
We beg you, the developer, please fix this issues on Android 11. Your emulator fork is the best on the github so I would love to keep enjoying it and getting new updates. Thanks a lot

**Comment by raelbbb** [comment]
Bom creio eu que o problema não seja devido aos celulares mas sim o aplicativo que está apresentando problema em todos os celulares

**Comment by FensBK** [comment]
Same problem. Galaxy S20 FE SD 865 Android 12. Had to rollback to 2.0-15110

**Comment by EKatowitz** [comment]
Same here - Moto G Stylus (2021)

I even tried wiping the app data and it still happens.

**Comment by raelbbb** [comment]
E aí pessoal a nova versão do aplicativo voltou ao normal?

**Comment by dochankpin** [comment]
Guys. Let's wait if the developer will fix this issue,
or if he will release any future updates. Anyway,
we'll talk about the error again ok?
Thank you for everyone's attention and support.
bye.

**Comment by RadSec16** [comment]
Same to me, Poco X3 pro on Android 11, It keeps appearing this message even when i close the app
