### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by persianstryx** [Bankaimaster999/Dolphin-MMJR2#69]
What exactly does disabling primitive restart on andreno mean? 
How do you turn off primitive restart on adreno..???

**Comment by Bankaimaster999** [comment]
Its a code within dolphin that they had for emulating games I think (not 100% sure) ...However; it was found in Dolphin MMJ code to be removed. Thus, a former MMJR tester Gamer64ytb edited MMJR2 code to remove it and he found that performance on his adreno device got a performance boost.
He passed on his findings to the Dolphin Devs as well and they confirmed that it did have an impact but for only adreno devices. As for why this happens they don't know yet but the performance improvements from it was good enough for them to disable it in their developer version and they plan to see if they can make it configurable or improve it for adreno devices.

As for MMJR2 it was also applied to it after further discussions with Gamer64ytb and reviewing the Dolphin devs conversation on the change and for MMJR (the one made from MMJ) - it was already removed from the beginning.

To be clear this is not a option to toggle; its removal or disabling the function within the code of the app; users don't have access to that unless you get the source code, disable/remove the necessary code and rebuild the app.

**Comment by persianstryx** [comment]
Does this mean that every source code after the update 15109 already has it
innately removed?..

**Comment by Bankaimaster999** [comment]
pretty much
