### ISSUE TITLE
Can't find drag IR pointer option

### ISSUE THREAD

**Issue by Ocel4do** [Bankaimaster999/Dolphin-MMJR2#72]
Where is it?

**Comment by Bankaimaster999** [comment]
.... um its there ....
Overlay controls -> IR (drag,etc), you can also use emulated joystick to force it out if its hiding (though it shouldn't be doing that) and there is also setting IR always to center.

Not sure what you mean since I and other users haven't encountered that issue so far ...

**Comment by Ocel4do** [comment]
What you said, thanks :)
