### ISSUE TITLE
Not able to enter Wii Menu channel

### ISSUE THREAD

**Issue by Ocel4do** [Bankaimaster999/Dolphin-MMJR2#73]
When I try to configure it, it says:

![Screenshot_2022-03-07-22-00-48-427_org dolphinemu mmjr](https://user-images.githubusercontent.com/100074505/157117299-0cb4ed54-1c7e-43f4-9d1e-68b657fd06c8.jpg)

What can I do?

**Comment by Ocel4do** [comment]
Always happens this. I close it, and enter it again.

**Comment by Ocel4do** [comment]
Please, give me a response :)

**Comment by Bankaimaster999** [comment]
> Please, give me a response :)

I'm no longer working on this build nor is the other dev so chances are this won't be fixed. Please use Dolphin Official build going forward or if you really don't want to then try Lumince build
